blog/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns("blog.views",
    url(r'^post$', 'post', name='post'),
    url(r'^post/(\d+)/edit$', 'post', name='edit'),
    url(r'^post/(.+)$', 'detail', name='detail'),
)

solog/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'SoloG.views.home', name='home'),
    # url(r'^SoloG/', include('SoloG.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('blog.urls', namespace="blog")),
    url(r'^$', 'blog.views.index', name="index"),
    url(r'^accounts/', include('account.urls', namespace='account')),
)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import urlencode
from django.utils.http import urlquote
from django.utils.translation import ugettext_lazy as _
from datetime import datetime


class BlogManager(models.Manager):
    def get_current(self):
        return self.get(id=1)


class Blog(models.Model):
    name = models.CharField(max_length=50, verbose_name=u"Blog Name")
    description = models.TextField(_(u"Blog Description"))

    objects = BlogManager()


FORMAT_CHOICES = (
    ('restructuredtext', 'reST (reStructuredText)'),
    ('textile', 'Textile'),
    ('markdown', 'Markdown'),
    ('html', 'HTML'),
    ('txt', 'Plain Text'),
)


class PostManager(models.Manager):
    def post(user, title, content, format='txt'):
        return self.create(
            user = user,
            title = title,
            content = content,
            content_format = format,
        )


class Post(models.Model):
    user = models.ForeignKey(User, related_name="entries")

    title = models.CharField(max_length=100)
    slug = models.SlugField()

    filename = models.CharField(max_length=255, null=True, blank=True)

    content = models.TextField(default="")
    content_html = models.TextField(default="")
    content_format = models.CharField(max_length='30', choices=FORMAT_CHOICES)

    is_published = models.BooleanField(default=True, db_index=True)

    created_at = models.DateTimeField(default=datetime.now)
    last_update_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return u"blog:detail", [self.slug or self.id]


class Version(models.Model):
    entry = models.ForeignKey(Post)
    revision = models.IntegerField()

    content = models.TextField()
    diff = models.TextField()
    edit_at = models.DateTimeField(auto_now_add=True)


class Images(models.Model):
    pass


class SyncActivity(models.Model):
    user = models.ForeignKey(User)
    description = models.TextField()
    post = models.ForeignKey(Post, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.description

blog/forms.py
from django import forms
from blog.models import Post

class EntryForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'content_format')

blog/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.markup.templatetags.markup import restructuredtext
from django.shortcuts import render_to_response, redirect, get_object_or_404, render
from django.template.context import RequestContext
from django.template.defaultfilters import linebreaksbr
from blog.forms import EntryForm
from blog.models import Post


def index(request):
    """
    Index page
    """
    query = Post.objects.filter(is_published=True).order_by('-created_at')
    results = {}
    if query.count():
        first_post = Post.objects.order_by('id')[0]
        last_post = query[0]
        years = range(first_post.created_at.year, last_post.created_at.year + 1)
        years.sort(reverse=True)

        for year in years:
            results[year] = query.filter(created_at__year=year)

    return render(request, "index.html", {'posts': query})


def format_content(format, content):
    depend = {
        'markdown': 'markdown',
    }
    try:
        if format == 'markdown':
            import markdown
            return markdown.markdown(content)
        elif format == 'txt':
            return linebreaksbr(content)
        elif format == 'html':
            return content
        elif format == 'textile':
            try:
                import textile
                return textile.textile(content)
            except ImportError:
                raise Exception(u"You must install PyTextile to use textile format.")
        elif format == 'restructuredtext':
            try:
                import docutils
                return restructuredtext(content)
            except ImportError:
                raise Exception(u"You must install docutils to use reST format.")

    except ImportError:
        raise Exception('You should install "%s" to use %s format.' % (depend.get(format),  format))


@login_required
def post(request, post_id=None):
    """
    post a new post
    """
    post = get_object_or_404(Post, id=post_id) if post_id else None
    if request.method == 'POST':
        form = EntryForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            try:
                post.content_html = format_content(post.content_format, post.content)
                post.save()
                return redirect(post.get_absolute_url())
            except Exception, e:
                messages.error(request, e.message)

    else:
        form = EntryForm(instance=post)

    context = {'form': form}
    return render_to_response("blog/post.html", context, RequestContext(request))


def detail(request, slug_or_id):
    if slug_or_id.isdigit():
        query = {'id': slug_or_id}
    else:
        query = {'slug': slug_or_id}

    post = get_object_or_404(Post, **query)

    context = {'post': post}
    return render(request, "blog/detail.html", context)

blog/templates/blog/detail.html
{% extends 'base.html' %}
{% load i18n markup %}
{% load humanize %}

{% block title %}{{ post.title }}{% endblock %}

{% block page_actions %}
    {% if user.is_authenticated %}
        <a class='btn btn-small ajaxable' href='{% url "blog:edit" post.id %}'>{% trans 'Edit' %}</a>
    {% endif %}
{% endblock %}

{% block content %}
    {% include "profile.html" %}
    <article>
        <header>
          <h1>
            <a href="{{ post.get_absolute_url }}"> {{ post.title }} </a>
          </h1>
        </header>

        {% autoescape off %}
        {{ post.content_html }}
        {% endautoescape %}

        <aside>
          {{ post.created_at|date }}
          {% if not post.last_update_at == post.created_at %}
            ( 更新: {{ post.last_update_at|naturalday }} )
          {% endif %}
        </aside>
    </article>

{% endblock %}

blog/templates/blog/post.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans 'Post' %}{% endblock %}

{% block content %}
    <form method='post' id='post-form'>
        {% csrf_token %}

        {{ form.as_p }}

        <p>
            <input type='submit' class='btn btn-small btn-primary' />
        </p>
    </form>
{% endblock %}

blog/templates/blog/search.html
{% load highlight %}
<ul>
{% for result in results %}
    {% with result.object as post %}
        <li class='result'>
            <a class='title' href='{{ post.get_absolute_url }}'>{% highlight post.title with q %}</a>
            <span class='content'>
                {% highlight post.content with q max_length 30 %}
            </span>
        </li>
    {% endwith %}
{% endfor %}
</ul>